#define REDIS_GIT_SHA1 "12430a92"
#define REDIS_GIT_DIRTY "     293"
#define REDIS_BUILD_ID "seojiung-ui-MacBookPro.local-1700125058"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
